/**
 * Name: Joshua Zhang
 * Date: Feburary 11, 2022
 * Section: CSE 154 AB
 *
 * It's the index.js file for cp3 fetch that provides all the functions and UI
 * for index.html to work properly. Basically, it uses api provided by a
 * website called Cheap Shark to show all the games on sale at the moment
 * the index.html is opened. All pictures generated by this file were from
 * the api. Users can search whatever game they want by providing details
 * such as name, price range, and etc..
 */

"use strict";
(function() {

  /**
   * Sets up the base url of cheap shark api to be used later.
   */
  const BASE_URL = "https://www.cheapshark.com/api/1.0/";

  window.addEventListener("load", init);

  /**
   * Initializes the window and sets up buttons of the web to work
   * properly.
   */
  function init() {
    currentDate();
    makeRequestDeal();
    id("search-btn").addEventListener("click", searchList);
    id("back-btn").addEventListener("click", backToMain);
  }

  /**
   * Making a fetching request on the deal information of top
   * 30 games matching the searching condition. If the request
   * is successful, processing the data recieved to show the
   * user the information. If the request failed and catch an
   * error, showing the error message to the users.
   */
  function makeRequestDeal() {
    let url = urlPreparerDeal();
    fetch(url)
      .then(statusCheck)
      .then(resp => resp.json())
      .then(processDataDeal)
      .catch(handleError);
  }

  /**
   * Taking in a certain id of game and making a fetching request
   * on the details of this specified game. If the request
   * is successful, processing the data recieved to show the
   * user the information. If the request failed and catch an
   * error, showing the error message to the users.
   * @param {Number} id - the number id of a certain game.
   */
  function makeRequestDetail(id) {
    let url = urlPreparerGame(id);
    fetch(url)
      .then(statusCheck)
      .then(resp => resp.json())
      .then(processDataGame)
      .catch(handleError);
  }

  /**
   * This function checks if the resp recieved from the fetching request
   * is valid. If not, this function will stop the process. Other than
   * that, this function returns the resp object for the next step of
   * processing.
   * @param {Object} resp - The object recieved from the fetching request.
   * @return {Object} - The object recieved from the fetching request that
   * has a valid status for next step of processing.
   */
  async function statusCheck(resp) {
    if (!resp.ok) {
      throw new Error(await resp.text());
    }
    return resp;
  }

  /**
   * This function takes in the error catched during the fetching request.
   * If an error is found, this function will show the error message on
   * the web page correctly along with notification and suggestion text.
   * This function will show the error mesage on different views of the
   * page depending on the current view.
   * @param {Error} err - The error message of the type of error.
   */
  function handleError(err) {
    let error = gen("p");
    error.textContent = "Error happens during fetching, please try again later";
    let message = gen("p");
    message.textContent = "Error reason: " + err;
    let view;
    if (id("details-bar").classList.contains("hidden")) {
      view = id("current-view");
    } else {
      view = id("details-bar");
    }
    view.innerHTML = "";
    view.appendChild(error);
    view.appendChild(message);
  }

  /**
   * Taking in the Json object resp and generating DOM object to contain the information
   * from the Json object in the form of bars. The users can view these views from the deal
   * view and the information of the games on the bars.
   * @param {Object} resp - A Json object contains data recieved from fetching with
   * an api following a certain searching condition.
   */
  function processDataDeal(resp) {
    for (let i = 0; i < resp.length; i++) {
      let data = resp[i];
      let container = gen("div");
      let left = gen("p");
      let right = gen("p");
      let img = gen("img");
      img.src = data.thumb;
      img.alt = data.title;
      left.textContent = data.title;
      messageMaker(right, data);
      container.id = data.gameID;
      container.appendChild(img);
      container.appendChild(left);
      container.appendChild(right);
      container.addEventListener("click", showDetail);
      container.classList.add("card");
      id("current-view").appendChild(container);
    }
  }

  /**
   * Taking in two objects right and data. This function will append the right DOM
   * object with information from the data object. By doing so, the features come
   * along with the price of the game will change when the order condition changes.
   * @param {Object} right - A DOM object with <p> tag that contains information
   * of games' price and other details depending on searching condition.
   * @param {Object} data - A Json object contains data recieved from fetching with a
   * certain api relating with a certain game.
   */
  function messageMaker(right, data) {
    right.textContent = "Deal Price: " + data.salePrice + "(" + data.normalPrice + ")";
    let options = qs("select");
    if (options[options.selectedIndex].value === "dealRating") {
      right.textContent += " Deal Rate: " + data.dealRating + "/10";
    } else if (options[options.selectedIndex].value === "metacritic") {
      right.textContent += " Metacritic Score: " + data.metacriticScore;
    } else if (options[options.selectedIndex].value === "reviews") {
      right.textContent += " Positive Review Rate: " + data.steamRatingPercent + "%";
    } else {
      right.textContent += " Saving Percentage: " + Math.floor(data.savings) + "%";
    }
  }

  /**
   * Accessing the details of a game from resp and fill the detail view with the
   * title, image, link, cheapest price, and a suggestion line for that game.
   * @param {Object} resp - The Json object with data recieved on a specific game
   * by fetching.
   */
  function processDataGame(resp) {
    let information = resp["info"];
    let cheapest = resp["cheapestPriceEver"];
    let img = gen("img");
    img.src = "https://cdn.cloudflare.steamstatic.com/steam/apps/";
    img.src += information.steamAppID + "/header.jpg";
    img.alt = information.title;
    let link = gen("a");
    link.href = "https://store.steampowered.com/app/"
    link.href += information.steamAppID;
    link.textContent = "Click this link to view the game in store.";
    link.target = "_blank";
    id("image").appendChild(img);
    id("title").textContent = "Game Title: " + information.title;
    id("title").textContent += "(" + information.steamAppID + ")";
    id("steam").appendChild(link);
    id("cheapest").textContent = "Cheapest price: " + cheapest.price + " dollars";
    id("suggestion").textContent = "Visiting the store for more information";
    id("suggestion").textContent += " or using the back button to go back.";
  }

  /**
   * Basing on the information provided by the index.html, this function
   * returns a string of url linking with a list of games satisfying
   * certain conditions.
   * @return {String} a string of url linking to a list of games.
   */
  function urlPreparerDeal() {
    let url = BASE_URL + "deals?storeID=1&pageSize=30"
    let onSale = "&onSale=" + qs('input[type="radio"]:checked').value;
    let options = id("selecting");
    let sortBy = "&sortBy=" + options[options.selectedIndex].value;
    if (options[options.selectedIndex].value === "dealRating") {
      sortBy = "";
    }
    let name = "";
    if (id("name").value !== "") {
      name = "&title=" + id("name").value;
    }
    let lowerPrice = "&lowerPrice=" + id("lower").value;
    let upperPrice = "&upperPrice=" + id("upper").value;
    url = url + sortBy + name + lowerPrice + upperPrice + onSale;
    return url;
  }

  /**
   * Hidding away the deals view and switch to the detail view.
   * Making a request for data of game with specific id.
   */
  function showDetail() {
    toggleViews();
    let id = this.id;
    makeRequestDetail(id);
  }

  /**
   * Taking in a number id and return a string url linking with
   * a game with this id.
   * @param {Number} id - a number representing the id of a game.
   * @return {String} a string of url linking with web of the game.
   */
  function urlPreparerGame(id) {
    let url = BASE_URL + "games?id=" + id;
    return url;
  }

  /**
   * Cleaning the current deals information and search
   * with new features.
   */
  function searchList() {
    id("current-view").innerHTML = "";
    makeRequestDeal();
  }

  /**
   * Cleaning all the information in the detail and switch
   * the view back to deals page.
   */
  function backToMain() {
    let information = qsa("#details-bar li");
    for (let i=0; i < information.length; i++) {
      information[i].innerHTML = "";
    }
    toggleViews();
  }

  /**
   * Showing the date in YY/MM/DD format on the web page.
   */
  function currentDate() {
    let date = new Date().toLocaleDateString();
    id("date").textContent = date;
  }

  /**
   * Allows users to switch views between the deals and the game details.
   */
  function toggleViews() {
    id("deal-view").classList.toggle("hidden");
    id("detail-view").classList.toggle("hidden");
  }

  /* --- CSE 154 HELPER FUNCTIONS --- */
  /**
   * Returns the DOM object with the given id attribute.
   * @param {string} name - element ID
   * @returns {object} DOM object associated with id (null if not found).
   */
  function id(name) {
    return document.getElementById(name);
  }

  /**
   * Returns the first DOM object that match the given selector.
   * @param {string} selector - query selector
   * @returns {object} - the DOM object matching the query.
   */
  function qs(selector) {
    return document.querySelector(selector);
  }

  /**
   * Returns an array of DOM objects that match the given selector.
   * @param {string} query - query selector
   * @returns {object[]} array of DOM objects matching the query.
   */
  function qsa(query) {
    return document.querySelectorAll(query);
  }

  /**
   * Returns a new element with the given tag name.
   * @param {string} tagName - HTML tag name for new DOM element.
   * @returns {object} New DOM object for given HTML tag.
   */
  function gen(tagName) {
    return document.createElement(tagName);
  }
})();